# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dag_manager_pb2 as dag__manager__pb2


class DagServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllCurveDags = channel.unary_unary(
        '/dagmanagerpb.DagService/GetAllCurveDags',
        request_serializer=dag__manager__pb2.CurveDagRequest.SerializeToString,
        response_deserializer=dag__manager__pb2.GetAllCurveDagsResponse.FromString,
        )


class DagServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllCurveDags(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DagServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllCurveDags': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllCurveDags,
          request_deserializer=dag__manager__pb2.CurveDagRequest.FromString,
          response_serializer=dag__manager__pb2.GetAllCurveDagsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dagmanagerpb.DagService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
